version: '3'
services:
  web:
    image: azhar321/paycricket:v1
    ports:
      - "8006:80"
    deploy:
      replicas: 3
  web2:
    image: azhar321/paybowlling:v1
    ports:
      - "8007:80"
    deploy:
      replicas: 3
